chartiq:
    resource: "@ChartiqBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de|es

homepage:
    path:   /
    defaults:  { _controller: LiveFeedBundle:Feeds:Home }
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de|es
    options: { i18n: false }

live_feed:
    resource: "@LiveFeedBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de|es

app:
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de|es
    resource: '@AppBundle/Controller/Web'
    type: annotation

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    defaults:
        _format: json
    prefix: /api/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


#root:
#    path: /commodities
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /commodities-brokers
#        permanent: true
#
