live_feed:
    resource: "@LiveFeedBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de

app:
    prefix: /{_locale}/
    requirements:
        _locale: en|fr|de
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


#root:
#    path: /commodities
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /commodities-brokers
#        permanent: true
#
